// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:9f0662cc-ad3d-4975-863d-297f37296ada",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_psa4dWqfr",
    "aws_user_pools_web_client_id": "6li02dgf5abdqrghjipsm6pq0p",
    "oauth": {}
};


export default awsmobile;
