// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:9f0662cc-ad3d-4975-863d-297f37296ada",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_psa4dWqfr",
    "aws_user_pools_web_client_id": "6li02dgf5abdqrghjipsm6pq0p",
    "oauth": {
        "domain": "conponod48e6428-d48e6428-dev.auth.us-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:4200/",
        "redirectSignOut": "http://localhost:4200/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://hjrgixjng5gfpk2b5eh7wyzuhm.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
